### ISSUE TITLE
Cluster health check doesn't work for natMap hosts

### ISSUE THREAD

**Issue by henryoswald** [sharelatex/redis-sharelatex#6]
The redis cluster health check pulls out all the nodes in the cluster and runs a ping against each one individually. It looks like it is using the linode internal ip address, not the ones mapped over to the proxy ip addresses via the natMap value. 

Standard pings work fine:
```
sessionRedisClient.ping (err, res)->
	console.log err, res, "ping result"
```

In the real time process `ho-docker` is currently setup as root when you ssh in to allow debugging on the k8 instance, health checks are also set to always return 200 for the time being. The config is correctly setup with the natmap values in settings.
```

> rake local:use[staging,02]
> kubectl get pods | grep real
real-time-stag-6bd89cb898-9xcdr                    1/1       Running             0          19m
real-time-stag-6bd89cb898-d5hxp                    1/1       Running             0          19m
> kubectl exec -it real-time-stag-6bd89cb898-9xcdr bash

```
I have also put some debug lines into redis-sharelatex on real time to log out some key values. 

If we can either make the current check work with natMap ips, or look at replacing it with a similar viable health check.

**Comment by briangough** [comment]
This was discussed in slack, and the health check was working again after a ghosttunnel restart.
